import { createHash, Hash } from "crypto";

import { IWritable } from "./internal";

const header: string = `/**
 * This file was generated by typescriptace.
 * SOURCE<<@0>>
 * SIGNED<<@1>>
 */`;

export abstract class TSModule implements IWritable {

  private static getHash(content: string): string {
    const hash: Hash = createHash("SHA512");
    hash.update(content);

    return hash.digest("base64");
  }

  public abstract breadcrumb(): string;

  public print(): string {
    const fmtHeader: string = header
      .replace("@0", this.constructor.name)
      .replace("@1", TSModule.getHash(""));

    return fmtHeader;
  }
}
